name = "zfit"
uuid = "d402d023-d064-498c-b940-ad3debf72f5c"
authors = ["Jonas Eschle <Jonas.Eschle@cern.ch>"]
version = "0.0.1"

[deps]
Distributions = "31c24e10-a181-5473-b8eb-7969acd0382f"

[compat]
julia = "1.6"
